### ISSUE TITLE
Segmentation fault / endless loop

### ISSUE THREAD

**Issue by alexsegura** [speckcommerce/speck#24]
I got this when running a fresh install. I was having a Segmentation Fault and had to activate XDebug to obtain this stack trace : 

<pre>
Fatal error: Maximum function nesting level of '100' reached, aborting! in /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php on line 44

Call Stack:
    1.6995    8860044   1. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:0
    1.6996    8860564   2. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.6996    8861172   3. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.6997    8861692   4. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.6997    8862308   5. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.6999    8862828   6. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.6999    8863452   7. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7000    8863972   8. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7000    8864580   9. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7001    8865108  10. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7001    8865716  11. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7001    8866276  12. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7002    8866904  13. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7003    8867424  14. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7003    8868032  15. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7003    8868552  16. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7004    8869160  17. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7004    8869680  18. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7004    8870288  19. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7005    8870808  20. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7005    8871416  21. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7006    8871936  22. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7006    8872544  23. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7007    8873064  24. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7007    8873672  25. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7007    8874192  26. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7008    8874800  27. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7008    8875320  28. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7008    8875928  29. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7009    8876452  30. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7009    8877060  31. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7010    8877580  32. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7010    8878188  33. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7010    8878708  34. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7011    8879316  35. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7011    8879836  36. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7011    8880444  37. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7012    8880964  38. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7012    8881572  39. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7013    8882092  40. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7013    8882700  41. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7014    8883220  42. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7014    8883828  43. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7014    8884348  44. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7014    8884956  45. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7015    8885476  46. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7015    8886084  47. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7016    8886604  48. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7016    8887212  49. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7017    8887732  50. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7017    8888340  51. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7018    8888860  52. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7018    8889468  53. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7019    8889988  54. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7019    8890596  55. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7019    8891116  56. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7020    8891724  57. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7020    8892244  58. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7020    8892852  59. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7021    8893372  60. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7021    8893980  61. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7022    8894500  62. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7022    8895108  63. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7023    8895628  64. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7023    8896236  65. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7024    8896756  66. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7024    8897364  67. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7025    8897884  68. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7025    8898492  69. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7025    8899012  70. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7026    8899620  71. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7026    8900140  72. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7026    8900748  73. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7027    8901268  74. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7027    8901876  75. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7028    8902396  76. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7028    8903004  77. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7029    8903524  78. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7029    8904132  79. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7029    8904656  80. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7030    8905264  81. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7030    8905784  82. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7030    8906392  83. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7031    8906912  84. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7031    8907520  85. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7032    8908040  86. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7032    8908648  87. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7033    8909168  88. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7033    8909776  89. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7034    8910296  90. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7034    8910904  91. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7034    8911424  92. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7035    8912032  93. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7035    8912552  94. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7036    8913160  95. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7036    8913680  96. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7036    8914288  97. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7037    8914808  98. serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
    1.7037    8915416  99. Zend\Stdlib\SplQueue->serialize() /home/alex/workspace/speck/vendor/ZF2/library/Zend/Stdlib/SplQueue.php:44
</pre>

Still haven't dig into the code to understand what happens and/or what uses a queue.

**Comment by alexsegura** [comment]
Hum, actually I misunderstood what happens, I'm doing something wrong : I have a 404. 

It is because I was on 

<code>http://localhost/speck/index.php</code> 

instead of 

<code>http://localhost/speck/index.php/</code>

Removing <code>index.php</code> or adding a <code>/</code> shows another error :-)

Maybe this is a Zend bug ? Commenting the BasicCheckoutStrategy constructor removed the error (of course !)

**Comment by nvahalik** [comment]
Cloned, ran speckinstall.sh, and getting Segmentation faults as well.  I'm using Zend Server and don't have Xdebug installed but it is segfaulting here:

SplQueue.php (line 44)

```
public function serialize()
{
    return serialize($this->toArray());
}
```

It segfaults after executing the toArray() method.

**Comment by EvanDotPro** [comment]
I believe this was fixed with this PR: https://github.com/speckcommerce/SpeckCheckout/pull/6

**Comment by EvanDotPro** [comment]
The submodule may need to be updated. I'll have @nclundsten check today.

**Comment by steverhoades** [comment]
Did you get feedback on this?  I am unable to replicate segfault after fix.

**Comment by nvahalik** [comment]
All fixed.

**Comment by nclundsten** [comment]
evandotpro wrote "I believe this was fixed with this PR: speckcommerce/SpeckCheckout#6"
this is resolved
